### PR TITLE
Turn tst/test.g into tst/basic.tst, add tst/testall.g

### PR DESCRIPTION
**Pull request by fingolfin**
Also set tst/testall.g as TestFile in PackageInfo.g

### CODE REVIEW

**Comment by frankluebeck** [comment]
The current `tst/test.g` is made for the `test` target in the `Makefile`. 

Currently I don't want to specify a test file in the `PackageInfo.g` file. Or is there now a documented setup in which this would be called? In particular, is guaranteed that EDIM is properly built before the test file is called?

**Comment by fingolfin** [comment]
We have been testing the TestFiles for several years now (and currently e.g.  also test them on Travis). And of course with properly built kernel modules, otherwise the package wouldn't even load due to its `AvailabilityTest`.

I am not sure what kind of "documentation" you'd expect for the test setup? Looking at the simple tests you have for EDIM, I'd expect thrm to pass in virtually any sane imaginable setup...

**Comment by alex-konovalov** [comment]
@frankluebeck We have "Tests files for a GAP package" section in the Example package for some time already, and in GAP 4.9 it is moving into the main manual: you may find it [here](https://www.gap-system.org/pub/gap/gap-4.9/beta/doc/ref/chap76.html#X8559D1FF7C9B7D14). Also the example package shows how to set it up - see the [`tst` directory](https://github.com/gap-packages/example/tree/master/tst). 

In fact, Example package shows even more - how to set up tools like Travis CI and CodeCov for continuous integration and code coverage statistics. But the initial setup (without Travis CI and CodeCov) is very simple and straightforward, exactly like in the changes that @fingolfin suggested.

If you wish to make the `.tst` file produced automatically (or semi-automatically) by pasting `tst/test.g` into GAP and then creating a `.tst` file containing all inputs and outputs, then this PR may be edited to leave `test.g` as is (or with minor modifications). Then you may later decide whether to keep the derived `.tst` file under version control or only include it in the release.

**Comment by fingolfin** [comment]
Rebased, and also updated `make test` to use `testall.g`

**Comment by frankluebeck** [comment]
@fingolfin said:
> And of course with properly built kernel modules, otherwise the package wouldn't even load due to its AvailabilityTest.

This is not correct, the package will load, but without the kernel function.

I have now added a `.tst` file. But I will only bind it to the `TestFile` entry of `PackageInfo.g` when it is guaranteed that this test file is only called when EDIM is fully installed with its kernel function. From the places I was pointed to I cannot conclude if this is the case.

**Comment by alex-konovalov** [comment]
I can not guarantee that nobody will every try to call `gap tst/testall.g` when EDIM is not installed with its kernel function. If in this case some informative message will appear in the test output, that will be useful.

But in the intended continuous integration tests we attempt to build as many packages as possible, and certainly do that before running package tests. EDIM builds fine there. Look at any Travis build for any recent pull request and search for lines with `TESTSUITE=testpackages`, and look in their test logs, for example:
* line 3690 in https://travis-ci.org/gap-system/gap/jobs/337202404
* line 3597 in https://travis-ci.org/gap-system/gap/jobs/337202402

Hence, if in these CI tests it will happen that the kernel module is missing, it will be a sign of problem that should be investigated (that was CI is intended for).

**Comment by fingolfin** [comment]
My bad, I did not realize edim loads without its kernel module.

But as @alex-konovalov said, the CI tests we setup always build edim, and they will always keep doing this; this is the "best" guarantee I can give, of course, as of course obviously anybody could take edim, and run the test file w/o compiling it... I guess what you wanted to say is that you don't want spurious complaints and issue reports caused by somebody running edim w/o having compiled the tests. Well, obviously in GAP nobody can speak for the whole group, but I am confident that I can guarantee that @alex-konovalov Chris, Markus etc. won't send reports for something like that. (And no automated reports are generated right now; but even if, they would take compilation of the kernel module into account, and so instead would report a compilation failure, not a test failure)

**Comment by fingolfin** [comment]
@frankluebeck I don't see a .tst file. Anyway, I just updated this PR with the latest changes you added to `tst/test.g` (and also changed this PR to not remove `tst/test.g`)

**Comment by frankluebeck** [comment]
Ok, I've uploaded a test file (just a single `.tst`-file  should be enough) and added a `TestFile` entry in `PackageInfo.g`.

Nevertheless, I still think that there should be a proper documentation saying how these `TestFile` entries are used. Pointing to a 8000 lines long cryptic build log is not a substitute for this.

In this case of EDIM, provided that the kernel function is installed, the test should run fine, independent of the set of other packages loaded.

**Comment by fingolfin** [comment]
I still don't understand what kind of "proper documentation" saying how these TestFile entries are used. In the dev manual, we currently say this:
```XML
If the record in the <F>PackageInfo.g</F> file of the package
(see <Ref BookName="Ref" Sect="The PackageInfo.g File"/>)
contains the component <C>TestFile</C> then the file given by the value
is read as a part of the regular &GAP; test suite,
see section <Ref Sect="Sect-TestSuite"/>.
So this file should contain <C>Test</C> statements for suitable
files that are part of the package distribution.
Since these tests are intended to be run regularly,
they should require not more than a few hours of CPU time.
(Of course also longer examples can make sense but they should not be
listed in the file given by the <C>TestFile</C> component.)
```

Could you please explain what kind of information would you want to make this "proper"? Then we could add it.

That said, I agree that in case of a test failure, it is not helpful if a package author is told "something is wrong with your package, here is this 8000 lines log file, please fix it". But that seems to be a completely different issue, and not that much about documentation. Granted, documentation could be written which explains how to understand such a log file, but I am not really sure how helpful that would be.

Still, I suspect what you are really asking for here is documentation on how to read those log files, including information about the environment in which they were created. At least that would be something I can understand.

**Comment by fingolfin** [comment]
Otherwise, I am somewhat sad that you just keep discarding my pull requests and redoing things differently. The .tst file you now added to EDIM is from my point of view strictly inferior to the one in this PR. With your new .tst file, one only sees if a function returns an unexpected result, but not what it is; so to debug it, one has to conduct additional steps. With the .tst file I made (and which you could have simple copied), one also saw the incorrect output, which in my experience often gives immediate additional clues about the source of the problem (which is esp. helpful when one receives reports from users which one cannot immediately reproduce locally).

Anyway, I will stop sending PRs from now on and only open issues, as I feel I am wasting my time otherwise.

**Comment by frankluebeck** [comment]
The cited documentation of `.TestFile` does not state that this is only called with fully installed packages. As far as I understood, tests are run with several GAP configurations (which ones?) and several sets of packages (none/default/all?). This is important information to know for preparing test files, because in general the output of calls in the test files can depend on the setup. So, this should be documented. (But we have already discussed all of this in the context of other packages.)

If there is a single test file, as in this case, one can specify this directly, as some documentation I was pointed to said. So, the indirection with a 'testall.g' seems unnecessary. And why does `testall.g` stop the GAP session from which it is called. I don't understand what you mean by "additional clues", the default 'Test` function always shows input/expected output/found output in case of a problem, this has nothing to do with a 'testall.g' file.

**Comment by alex-konovalov** [comment]
> The cited documentation of .TestFile does not state that this is only called with fully installed packages. As far as I understood, tests are run with several GAP configurations (which ones?) and several sets of packages (none/default/all?). 

Yes, it does not say which set of packages is loaded when the test is run. In real life there may be many different sets of packages loaded on user machines when they will be working with your package. Some of them may have some compiled or not, loaded by default or not, etc.

We can not model each and every situation in regression tests, but we run usually 32 and 64-bit builds on Linux and macOS. It may be not practically feasible to do this for package authors, so we are happy to do it on our test infrastructure and report problems. 

The other dimension to testing is indeed added by the set of loaded packages. There are three options here:
* With no packages loaded (GAP started with `-r` option)
* With all packages loaded with `LoadAllPackages()`      
* With default packages loaded at GAP startup          

which are used as approximation of various settings. Package authors can run the standard test of their package in all these three scenarious using 

    make testpackage PKGNAME=pkgname

as documented [here](https://www.gap-system.org/pub/gap/gap-4.9/beta/doc/ref/chap76.html#X866ADD4E814A54F0). Of course, for the middle scenario `LoadAllPackages()` should work. Alternatively, they may also call `TestPackage(pkgname);` from the GAP session and then tests will run just once, with the currently loaded set of packages. 

Max quoted documentation from the doc/dev manual, which is a bit outdated. A newer, recently revised text is in [76.18-1 Tests files for a GAP package](https://www.gap-system.org/pub/gap/gap-4.9/beta/doc/ref/chap76.html#X85CA2F547CF87666) from GAP 4.9.0 - please have a look. 

> This is important information to know for preparing test files, because in general the output of calls in the test files can depend on the setup. So, this should be documented. (But we have already discussed all of this in the context of other packages.)

An ideal test should always pass, and there are various techniques for that (properly documenting package dependencies; suppressing output with `;;`, checking properties of the output instead of its exact printing, etc). Sometimes several iterations may be required to clean up the tests. If the output is varying, I would suggest first to have it like in the test with default packages, have a round of testing, and then see how to adjust tests to avoid diffs elsewhere. 

> If there is a single test file, as in this case, one can specify this directly, as some documentation I was pointed to said. So, the indirection with a 'testall.g' seems unnecessary. And why does testall.g stop the GAP session from which it is called. I don't understand what you mean by "additional clues", the default 'Test` function always shows input/expected output/found output in case of a problem, this has nothing to do with a 'testall.g' file.

`TestDirectory` was introduced in GAP 4.8. This is [its documentation in GAP 4.9.0](https://www.gap-system.org/pub/gap/gap-4.9/beta/doc/ref/chap7.html#X87AF67528799481F
). The idea is to make adding new tests as simple as possible, just by dropping a new test file in a test directory. You can of course continue with a single `.tst` file, but in the future, if you will e.g, decide test files for manual examples, one per chapter, or add some extra test file to cover some special cases, then `TestDirectory` is the most optimal way to run them all. The fact that it stops GAP is quite convenient. First, you need to run this test in a clean GAP session, like it is usually done by the GAP test suite. Second, it signals the exit code, and it is convenient to fail the test automatically.

A separate remark about the log file 8000 long - I was referring to very long files above, namely 
- line 3690 in https://travis-ci.org/gap-system/gap/jobs/337202404
- line 3597 in https://travis-ci.org/gap-system/gap/jobs/337202402
to demonstrate to you that EDIM build works there, as you have asked me. Of course, it is long, since it builds GAP and all packages from scratch, but package authors are not expected to refer to THOSE Travis builds in everyday development. Instead, they are advised to see Docker builds that use the prebuilt GAP container.

For example
* just about 700 lines when test passes for Alnuth:  https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9/jobs/336971144
* 941 lines when test fails for Wedderga: https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging/jobs/336971300

In the case of Wedderga, it finishes with the summary:
```
######################################################################
#
# TESTS SUMMARY
#
######################################################################

Package name                                         :  wedderga
With no packages loaded (GAP started with -r option) :  11 DIFFS
With all packages loaded with LoadAllPackages()      :  1 DIFFS
With default packages loaded at GAP startup          :  PASS

######################################################################\n

# WHY DOES A PACKAGE TEST MIGHT FAIL?

1. Check log files for each of the three scenarios:
- when GAP is started with only required packages; 
- with all packages loaded; 
- and with default set of packages. 

2. If any of the three test logs contain diffs (marked as
`########> Diff`), the test is reported as failed.

3. If the package is not loadable because its build fails, 
check the latest build log for the Docker container: 
https://hub.docker.com/r/gapsystem/gap-docker-stable-4.9/builds/

4. If you need to investigate the problem in the same 
environment that is used for these tests, you may download 
and run the Docker container following instructions given at
https://hub.docker.com/r/gapsystem/gap-docker-stable-4.9/

5. If all three logs looks good to you, it could be that it 
is still not possible to detect the status of your test, for
example, if you are still using `ReadTest`. Please consider
using `TestDirectory()` instead. For more information, see
https://github.com/gap-system/gap/wiki/Status-of-standard-tests-in-GAP-packages

######################################################################
```
preceded by three test log files, starting around line 500. So I can see, as a package author, that tests pass with default packages, and fail with other combinations (We are going to improve this in the coming release).

Do you find the explanation `WHY DOES A PACKAGE TEST MIGHT FAIL?` above useful? If you have any improvements of its wording, you can submit a pull request with your modifications to this file https://github.com/gap-system/gap-docker-pkg-tests-master/blob/master/HELP.md, and I will then propagate it to other builds.

**Comment by fingolfin** [comment]
@frankluebeck your .tst file does this:
```
gap> ElementaryDivisorsPPartRk(mat2, 2)=[ 34, 13, 10, 10, 0 ];
true
```
In case `ElementaryDivisorsPPartRk` returns a wrong result, then the only thing the `Test` output tells one that there was a wrong result, but not what it was. The .tst file I provided does this:
```
gap> ElementaryDivisorsPPartRk(mat2, 2);
[ 34, 13, 10, 10, 0 ]
```
Then in case of a failure, one also knows what was actually returned. I already described why this can be helpful.

**Comment by frankluebeck** [comment]
@alex-konovalov: Thanks for the link to: https://www.gap-system.org/pub/gap/gap-4.9/beta/doc/ref/chap76.html#X866ADD4E814A54F0

I was not aware of that function which is indeed helpful.

**Comment by frankluebeck** [comment]
@fingolfin: Now I understand that you were referring to the actual tests inside the test file and not the setup.  Tests for equality have the advantage that the output is more robust with respect to future changes of Print and View methods.

**Pull request closed without merging**
